package andrey.dev.UserInterface.ConsoleListener;

public enum Commands {
    USER_CREATE, SHOW_ALL_USERS, ACCOUNT_CREATE, ACCOUNT_CLOSE, ACCOUNT_DEPOSIT, ACCOUNT_TRANSFER,
    ACCOUNT_WITHDRAW, ACCOUNT_ADDER, ERROR
}
